// Question bank data for interview practice
export type QuestionType = 'technical' | 'behavioral' | 'system-design' | 'situational';
export type Language = 'zh' | 'en';

export interface Question {
  id: string;
  type: QuestionType;
  language: Language;
  question: string;
  hint?: string;
  tags: string[];
}

export const QUESTION_BANK: Question[] = [
  // ===== Technical Questions (技術問題) =====
  {
    id: 'tech-001',
    type: 'technical',
    language: 'en',
    question: 'Explain the difference between var, let, and const in JavaScript.',
    hint: 'Cover hoisting, reassignment, and block scope',
    tags: ['JavaScript', 'ES6', 'Variables'],
  },
  {
    id: 'tech-002',
    type: 'technical',
    language: 'en',
    question: 'What is the Virtual DOM and how does React use it?',
    hint: 'Explain reconciliation and diffing algorithm',
    tags: ['React', 'Virtual DOM', 'Performance'],
  },
  {
    id: 'tech-003',
    type: 'technical',
    language: 'en',
    question: 'Describe the difference between SQL and NoSQL databases.',
    hint: 'Cover ACID vs BASE, schema, scaling',
    tags: ['Database', 'SQL', 'NoSQL'],
  },
  {
    id: 'tech-004',
    type: 'technical',
    language: 'en',
    question: 'What is the event loop in JavaScript?',
    hint: 'Explain call stack, task queue, and microtask queue',
    tags: ['JavaScript', 'Event Loop', 'Async'],
  },
  {
    id: 'tech-005',
    type: 'technical',
    language: 'en',
    question: 'Explain RESTful API design principles.',
    hint: 'Cover HTTP methods, status codes, statelessness',
    tags: ['API', 'REST', 'HTTP'],
  },
  {
    id: 'tech-006',
    type: 'technical',
    language: 'en',
    question: 'What is the difference between == and === in JavaScript?',
    hint: 'Explain type coercion vs strict equality',
    tags: ['JavaScript', 'Type Coercion'],
  },
  {
    id: 'tech-007',
    type: 'technical',
    language: 'en',
    question: 'What is the purpose of TypeScript and what are its key features?',
    hint: 'Cover static typing, interfaces, generics',
    tags: ['TypeScript', 'JavaScript', 'Types'],
  },
  {
    id: 'tech-008',
    type: 'technical',
    language: 'en',
    question: 'Explain CSS Flexbox and when you would use it over CSS Grid.',
    hint: 'Cover main axis, cross axis, use cases',
    tags: ['CSS', 'Flexbox', 'Layout'],
  },
  {
    id: 'tech-009',
    type: 'technical',
    language: 'en',
    question: 'What is Docker and why is it used?',
    hint: 'Cover containers, images, isolation, CI/CD',
    tags: ['Docker', 'DevOps', 'Containers'],
  },
  {
    id: 'tech-010',
    type: 'technical',
    language: 'en',
    question: 'Explain the concept of microservices architecture.',
    hint: 'Cover decomposition, API communication, trade-offs',
    tags: ['Microservices', 'Architecture', 'Distributed Systems'],
  },
  {
    id: 'tech-011',
    type: 'technical',
    language: 'zh',
    question: '請說明 React 的生命週期方法以及何時會用到它們。',
    hint: '涵蓋掛載、更新、卸載階段',
    tags: ['React', 'Life Cycle', 'Components'],
  },
  {
    id: 'tech-012',
    type: 'technical',
    language: 'zh',
    question: '什麼是 HTTP？請求與回應的結構是什麼？',
    hint: '涵蓋請求方法、狀態碼、表頭、主體',
    tags: ['HTTP', 'Network', 'Web'],
  },
  {
    id: 'tech-013',
    type: 'technical',
    language: 'zh',
    question: '說明 JavaScript 中的閉包（Closure）是什麼以及它的應用場景。',
    hint: '涵蓋詞法作用域、私有變數、工廠函數',
    tags: ['JavaScript', 'Closure', 'Functional Programming'],
  },
  {
    id: 'tech-014',
    type: 'technical',
    language: 'zh',
    question: '什麼是 Promise？它如何解決回調地獄的問題？',
    hint: '涵蓋 then/catch、async/await、錯誤處理',
    tags: ['JavaScript', 'Promise', 'Async'],
  },
  {
    id: 'tech-015',
    type: 'technical',
    language: 'zh',
    question: '說明 Git 的常見指令如 merge、rebase、cherry-pick 的使用情境。',
    hint: '涵蓋分支策略、衝突處理',
    tags: ['Git', 'Version Control'],
  },
  {
    id: 'tech-016',
    type: 'technical',
    language: 'zh',
    question: '什麼是 TypeScript 的介面（Interface）與類型（Type）的差別？',
    hint: '涵蓋繼承、宣告合併、適用場景',
    tags: ['TypeScript', 'Types', 'Interfaces'],
  },
  {
    id: 'tech-017',
    type: 'technical',
    language: 'zh',
    question: '說明 JWT（JSON Web Token）的工作原理與使用場景。',
    hint: '涵蓋認證流程、優缺點',
    tags: ['JWT', 'Authentication', 'Security'],
  },
  {
    id: 'tech-018',
    type: 'technical',
    language: 'zh',
    question: '什麼是 Webpack 或 Vite？它們解決什麼問題？',
    hint: '涵蓋模組打包、開發體驗、效能優化',
    tags: ['Webpack', 'Vite', 'Build Tools'],
  },

  // ===== Behavioral Questions (行為問題) =====
  {
    id: 'beh-001',
    type: 'behavioral',
    language: 'en',
    question: 'Tell me about a time when you had to work with a difficult team member.',
    hint: 'Use STAR method, focus on your approach and outcome',
    tags: ['Teamwork', 'Conflict Resolution'],
  },
  {
    id: 'beh-002',
    type: 'behavioral',
    language: 'en',
    question: 'Describe a situation where you had to meet a tight deadline.',
    hint: 'Show prioritization, time management, and delivery',
    tags: ['Time Management', 'Pressure'],
  },
  {
    id: 'beh-003',
    type: 'behavioral',
    language: 'en',
    question: 'Tell me about a time you made a mistake at work. How did you handle it?',
    hint: 'Honesty, accountability, and learning from mistakes',
    tags: ['Accountability', 'Growth'],
  },
  {
    id: 'beh-004',
    type: 'behavioral',
    language: 'en',
    question: 'Describe a project you are most proud of.',
    hint: 'Highlight your specific contribution and impact',
    tags: ['Achievement', 'Motivation'],
  },
  {
    id: 'beh-005',
    type: 'behavioral',
    language: 'en',
    question: 'How do you handle disagreements with your manager or lead?',
    hint: 'Show respect, communication skills, and professionalism',
    tags: ['Communication', 'Professional Relationships'],
  },
  {
    id: 'beh-006',
    type: 'behavioral',
    language: 'en',
    question: 'Tell me about a time you had to learn a new technology quickly.',
    hint: 'Show learning ability, initiative, and adaptability',
    tags: ['Learning', 'Adaptability'],
  },
  {
    id: 'beh-007',
    type: 'behavioral',
    language: 'zh',
    question: '請說明一次你與團隊成員發生衝突的經驗，你是如何處理的？',
    hint: '使用 STAR 法，強調你的處理方式與結果',
    tags: ['團隊合作', '衝突解決'],
  },
  {
    id: 'beh-008',
    type: 'behavioral',
    language: 'zh',
    question: '描述一次你需要在緊迫期限內完成任務的經驗。',
    hint: '展示優先排序、時間管理與交付能力',
    tags: ['時間管理', '壓力處理'],
  },
  {
    id: 'beh-009',
    type: 'behavioral',
    language: 'zh',
    question: '請分享一個你在工作上犯過的錯誤，以及你如何面對與解決。',
    hint: '誠實、負責、從錯誤中學習',
    tags: ['負責', '成長'],
  },
  {
    id: 'beh-010',
    type: 'behavioral',
    language: 'zh',
    question: '你認為自己最大的優點與缺點是什麼？',
    hint: '真誠展現自我認知，並說明如何在工作中發揮或改善',
    tags: ['自我認知', '成長心態'],
  },
  {
    id: 'beh-011',
    type: 'behavioral',
    language: 'zh',
    question: '請說明你對加班的看法，以及你如何平衡工作與生活。',
    hint: '展示價值觀、時間管理與健康的工作態度',
    tags: ['價值觀', '工作態度'],
  },

  // ===== System Design Questions (系統設計) =====
  {
    id: 'sys-001',
    type: 'system-design',
    language: 'en',
    question: 'Design a URL shortening service like Bitly.',
    hint: 'Consider data model, hashing, sharding, and analytics',
    tags: ['URL Shortening', 'Database Design', 'Scalability'],
  },
  {
    id: 'sys-002',
    type: 'system-design',
    language: 'en',
    question: 'Design a chat messaging system like WhatsApp.',
    hint: 'Cover real-time delivery, offline messages, media handling',
    tags: ['Real-time', 'Messaging', 'WebSocket'],
  },
  {
    id: 'sys-003',
    type: 'system-design',
    language: 'en',
    question: 'Design a rate limiter for API requests.',
    hint: 'Consider algorithms, distributed systems, and storage',
    tags: ['Rate Limiting', 'API Design', 'Algorithms'],
  },
  {
    id: 'sys-004',
    type: 'system-design',
    language: 'en',
    question: 'Design a recommendation system for a video streaming platform.',
    hint: 'Cover collaborative filtering, content-based, and hybrid approaches',
    tags: ['Recommendation', 'Machine Learning', 'Scalability'],
  },
  {
    id: 'sys-005',
    type: 'system-design',
    language: 'en',
    question: 'Design the architecture for a social media news feed.',
    hint: 'Consider fan-out, pull vs push, caching strategies',
    tags: ['News Feed', 'Distributed Systems', 'Caching'],
  },
  {
    id: 'sys-006',
    type: 'system-design',
    language: 'zh',
    question: '設計一個類似 Yelp 的餐廳推薦系統。',
    hint: '涵蓋搜尋引擎、評分演算法、地圖整合',
    tags: ['推薦系統', '搜尋', 'LBS'],
  },
  {
    id: 'sys-007',
    type: 'system-design',
    language: 'zh',
    question: '設計一個分散式限流器（Distributed Rate Limiter）。',
    hint: '涵蓋令牌桶、滑動視窗、Redis 實現',
    tags: ['限流', '分散式系統', 'Redis'],
  },
  {
    id: 'sys-008',
    type: 'system-design',
    language: 'zh',
    question: '設計一個即時多人遊戲的後端架構。',
    hint: '涵蓋低延遲、狀態同步、房間管理',
    tags: ['遊戲', '即時系統', 'WebSocket'],
  },

  // ===== Situational Questions (情境題) =====
  {
    id: 'sit-001',
    type: 'situational',
    language: 'en',
    question: 'Your manager assigns you a task you think is unnecessary. What do you do?',
    hint: 'Show communication, respect for authority, and problem-solving',
    tags: ['Communication', 'Problem Solving', 'Attitude'],
  },
  {
    id: 'sit-002',
    type: 'situational',
    language: 'en',
    question: 'You discover a teammate has been taking credit for your work. How do you respond?',
    hint: 'Balance professionalism, direct communication, and protecting your work',
    tags: ['Professionalism', 'Conflict', 'Communication'],
  },
  {
    id: 'sit-003',
    type: 'situational',
    language: 'en',
    question: 'Your project is behind schedule due to unexpected technical challenges. What do you do?',
    hint: 'Show proactive communication, prioritization, and delivery management',
    tags: ['Project Management', 'Communication', 'Problem Solving'],
  },
  {
    id: 'sit-004',
    type: 'situational',
    language: 'en',
    question: 'You receive negative feedback from a code review. How do you handle it?',
    hint: 'Show openness to feedback, growth mindset, and professionalism',
    tags: ['Feedback', 'Growth', 'Code Quality'],
  },
  {
    id: 'sit-005',
    type: 'situational',
    language: 'en',
    question: 'You are asked to estimate the time for a project with many unknowns. How do you approach it?',
    hint: 'Show estimation techniques, transparency, and risk management',
    tags: ['Estimation', 'Risk Management', 'Communication'],
  },
  {
    id: 'sit-006',
    type: 'situational',
    language: 'zh',
    question: '你正在趕一個重要專案，但突然被要求接手另一個緊急任務。你會怎麼處理？',
    hint: '展示優先排序、溝通協調與時間管理能力',
    tags: ['優先排序', '溝通', '時間管理'],
  },
  {
    id: 'sit-007',
    type: 'situational',
    language: 'zh',
    question: '如果你發現產品的某個功能有嚴重的 bug，但團隊認為不緊急，你會怎麼做？',
    hint: '展示風險意識、說服技巧與責任感',
    tags: ['風險意識', '說服技巧', '責任感'],
  },
  {
    id: 'sit-008',
    type: 'situational',
    language: 'zh',
    question: '你被分配到一個你不熟悉的技術領域，你會如何快速上手？',
    hint: '展示學習能力、主動性與資源運用',
    tags: ['學習能力', '主動性', '適應力'],
  },
  {
    id: 'sit-009',
    type: 'situational',
    language: 'zh',
    question: '如果在會議中，你的想法被上級否決，但你仍然相信它是對的，你會怎麼做？',
    hint: '展示對上級的尊重、溝通技巧與執行力',
    tags: ['溝通', '尊重', '執行力'],
  },
];

export const QUESTION_TYPE_LABELS = {
  technical: { zh: '技術問題', en: 'Technical' },
  behavioral: { zh: '行為問題', en: 'Behavioral' },
  'system-design': { zh: '系統設計', en: 'System Design' },
  situational: { zh: '情境題', en: 'Situational' },
} as const;
